version: '3.8'

volumes:
  mysql-data: ~

services:
  mysql-db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - ./my.cnf:/etc/mysql/conf.d/config-file.cnf #./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: root
  #  command:
